In [111]:
import numpy as np
from typing import Self
from numpy.typing import NDArray
from jaxtyping import Float


type Features = Float[NDArray, 'samples features']
type Weights = Float[NDArray, 'features 1']
type Target = Float[NDArray, 'samples 1']
type Prediction = Float[NDArray, 'samples 1']

class linear_regression:
    def __init__(self):
        self._fitted: bool = False
        self._weights: Weights

    def coef_(self):
        print(self._weights)
        
    def fit(self, X: Features, y: Target, alpha: float=0.01) -> Self:
        print(type(X))
        w = np.ones(X.shape[1])
        
        X = X.copy()
        X[:, 0] = 1
        # y.reshape(-1, 1)
        print(X, w, y, sep='\n')
        def gradient(X: Features, w: Weights, y: Target) -> Weights:
            return X.T @ (X @ w - y)

        for _ in range(1000):
            w = w - alpha * gradient(X, w, y)

        self._fitted = True
        self._weights = w
        return self
        
    def predict(self, X: Features) -> Prediction:
        if self._fitted:
            return X @ self._weights
        else:
            raise OperationError('model is not fitted')

In [119]:
import numpy as np

np.random.seed(42)
X = np.array([[i, i*2] for i in range(1, 21)])
# y = 2*x₁ + 0.5*x₂ + шум
y = np.array([2*x[0] + 0.5*x[1] + np.random.normal(0, 0.5) for x in X])

# Разделение
split_idx = 15
X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

In [120]:
reg_savkit = linear_regression()
reg_savkit.fit(X, y)
reg.coef_

<class 'numpy.ndarray'>
[[ 1  2]
 [ 1  4]
 [ 1  6]
 [ 1  8]
 [ 1 10]
 [ 1 12]
 [ 1 14]
 [ 1 16]
 [ 1 18]
 [ 1 20]
 [ 1 22]
 [ 1 24]
 [ 1 26]
 [ 1 28]
 [ 1 30]
 [ 1 32]
 [ 1 34]
 [ 1 36]
 [ 1 38]
 [ 1 40]]
[1. 1.]
[ 3.24835708  5.93086785  9.32384427 12.76151493 14.88292331 17.88293152
 21.78960641 24.38371736 26.76526281 30.27128002 32.76829115 35.76713512
 39.12098114 41.04335988 44.13754108 47.71885624 50.49358444 54.15712367
 56.54598796 59.29384815]


/tmp/ipykernel_10651/1403173382.py:29: RuntimeWarning: overflow encountered in matmul
  return X.T @ (X @ w - y)
/tmp/ipykernel_10651/1403173382.py:32: RuntimeWarning: invalid value encountered in subtract
  w = w - alpha * gradient(X, w, y)


array([0.59004352, 1.18008705])

In [106]:
X[:, 0]

array([0, 1, 2])

In [121]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(X, y)
reg.coef_

array([0.59004352, 1.18008705])